### ISSUE TITLE
HTML reference-list disappears in Quarto HTML output

### ISSUE THREAD

**Issue by LibrEars** [jalvesaq/zotcite#55]
Hi again =)

I noticed that by using the `zotcite.py` filter for quarto my reference list disappears in the HTML output (book project). Single references still show up when hovering over the link in the text with the mouse. I use the quarto version: 1.2.267

yaml to reproduce issue (see [quarto books](https://quarto.org/docs/books/)):

```
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
filters:
  - /path/to/zotcite/python3/zotref.py   # exchange with your path to filter

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
```

Then add some reference in e.g. intro.qmd and preview HTML with `quarto preview mybook`

**Comment by jalvesaq** [comment]
Thanks for reporting the issue, but I have never worked on a book project with Quarto. So, I would need a complete minimal project to replicate the issue, perhaps a `tar.gz` or `zip` with all the required files. I would only replace the references with ones from my Zotero database.

**Comment by LibrEars** [comment]
thank you for the quick reply. Here is a zip with a skeleton of a book (github does not allow tar.gz):

[myproject.zip](https://github.com/jalvesaq/zotcite/files/9984199/myproject.zip

**Comment by jalvesaq** [comment]
It seems that citeproc is running before zotref.py. That is when zotref.py strips the citation keys from its visible part citeproc has already failed to find the citations.

What worked for me was.
1. Put in _quarto.yaml:

```yaml
citeproc: false
bibliography:
  - references.bib
  - myproject_zotcite.bib 
```

Run quarto in the terminal:

```sh
quarto render . pandoc-args -F /path/to/zotcite/python3/zotref.py --citeproc
```

This way we guarantee that pandoc will run zotref.py before citeproc.
